# Generated by Django 5.1.4 on 2024-12-15 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_remove_todoitem_category_todoitem_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todo_items",
                to="todo.category",
            ),
        ),
    ]
